imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

services:
    kernel.listener.send_error_to_mail_listener_name:
        class: Application\Sonata\ErrorsBundle\Listener\SendErrorToMailListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

twig:
    exception_controller: Application\Sonata\ErrorsBundle\Controller\ErrorsController::showAction
